const PREFIX = '';

export const REQUEST_MY_ASSIGNED_TEST = `${PREFIX}REQUEST_MY_ASSIGNED_TEST`;
export const RECEIVE_MY_ASSIGNED_TEST = `${PREFIX}RECEIVE_MY_ASSIGNED_TEST`;

export const REQUEST_MY_ASSIGNED_QUESTIONS = `${PREFIX}REQUEST_MY_ASSIGNED_QUESTIONS`;
export const RECEIVE_MY_ASSIGNED_QUESTIONS = `${PREFIX}RECEIVE_MY_ASSIGNED_QUESTIONS`;

export const REQUEST_ANSWER_SUBMIT = `${PREFIX}REQUEST_ANSWER_SUBMIT`;
export const RECEIVE_ANSWER_SUBMIT = `${PREFIX}RECEIVE_ANSWER_SUBMIT`;

export const REQUEST_ALL_MY_ASSIGNED_TEST = `${PREFIX}REQUEST_ALL_MY_ASSIGNED_TEST`;
export const RECEIVE_ALL_MY_ASSIGNED_TEST = `${PREFIX}RECEIVE_ALL_MY_ASSIGNED_TEST`;
