const PREFIX = '';

export const REQUEST_USER_LOGIN = `${PREFIX}REQUEST_USER_LOGIN`;
export const RECEIVE_USER_LOGIN = `${PREFIX}RECEIVE_USER_LOGIN`;

export const REQUEST_ALL_TEST_CATEGORY = `${PREFIX}REQUEST_ALL_TEST_CATEGORY`;
export const RECEIVE_ALL_TEST_CATEGORY = `${PREFIX}RECEIVE_ALL_TEST_CATEGORY`;

export const REQUEST_SAVE_CATEGORY = `${PREFIX}REQUEST_SAVE_CATEGORY`;
export const RECEIVE_SAVE_CATEGORY = `${PREFIX}RECEIVE_SAVE_CATEGORY`;

export const REQUEST_CATEGORY_INFO = `${PREFIX}REQUEST_CATEGORY_INFO`;
export const RECEIVE_CATEGORY_INFO = `${PREFIX}RECEIVE_CATEGORY_INFO`;

export const REQUEST_ALL_BY_CATEGORY = `${PREFIX}REQUEST_ALL_BY_CATEGORY`;
export const RECEIVE_ALL_BY_CATEGORY = `${PREFIX}RECEIVE_ALL_BY_CATEGORY`;

export const REQUEST_REGISTER_MANAGER = `${PREFIX}REQUEST_REGISTER_MANAGER`;
export const RECEIVE_REGISTER_MANAGER = `${PREFIX}RECEIVE_REGISTER_MANAGER`;

export const REQUEST_QUESTION_BANK_INFO = `${PREFIX}REQUEST_QUESTION_BANK_INFO`;
export const RECEIVE_QUESTION_BANK_INFO = `${PREFIX}RECEIVE_QUESTION_BANK_INFO`;

export const REQUEST_CATEGORY_GROUPING = `${PREFIX}REQUEST_CATEGORY_GROUPING`;
export const RECEIVE_CATEGORY_GROUPING = `${PREFIX}RECEIVE_CATEGORY_GROUPING`;

export const REQUEST_ALL_MANAGER_INFO = `${PREFIX}REQUEST_ALL_MANAGER_INFO`;
export const RECEIVE_ALL_MANAGER_INFO = `${PREFIX}RECEIVE_ALL_MANAGER_INFO`;

export const REQUEST_MANAGER_INFO = `${PREFIX}REQUEST_MANAGER_INFO`;
export const RECEIVE_MANAGER_INFO = `${PREFIX}RECEIVE_MANAGER_INFO`;

export const REQUEST_USER_CREDENTIAL = `${PREFIX}REQUEST_USER_CREDENTIAL`;
export const RECEIVE_USER_CREDENTIAL = `${PREFIX}RECEIVE_USER_CREDENTIAL`;

export const REQUEST_QUESTION_BANK_GROUPING = `${PREFIX}REQUEST_QUESTION_BANK_GROUPING`;
export const RECEIVE_QUESTION_BANK_GROUPING = `${PREFIX}RECEIVE_QUESTION_BANK_GROUPING`;

export const REQUEST_QUESTION_ANSWER_LIST = `${PREFIX}REQUEST_QUESTION_ANSWER_LIST`;
export const RECEIVE_QUESTION_ANSWER_LIST = `${PREFIX}RECEIVE_QUESTION_ANSWER_LIST`;

export const REQUEST_FILTERED_LIST = `${PREFIX}REQUEST_FILTERED_LIST`;
export const RECEIVE_FILTERED_LIST = `${PREFIX}RECEIVE_FILTERED_LIST`;

export const REQUEST_FILTERED_QB_LIST = `${PREFIX}REQUEST_FILTERED_QB_LIST`;
export const RECEIVE_FILTERED_QB_LIST = `${PREFIX}RECEIVE_FILTERED_QB_LIST`;

export const REQUEST_QB_TEMPLATE = `${PREFIX}REQUEST_QB_TEMPLATE`;

export const REQUEST_QB_UPLOAD = `${PREFIX}REQUEST_QB_UPLOAD`;
export const RECEIVE_QB_UPLOAD = `${PREFIX}RECEIVE_QB_UPLOAD`;

export const RECEIVE_QB_MODEL_VIEW = `${PREFIX}RECEIVE_QB_MODEL_VIEW`;

export const RECEIVE_QB_SELECTED_LIST = `${PREFIX}RECEIVE_QB_SELECTED_LIST`;

export const REQUEST_UPDATE_MANAGER_INFO = `${PREFIX}REQUEST_UPDATE_MANAGER_INFO`;
export const RECEIVE_UPDATE_MANAGER_INFO = `${PREFIX}RECEIVE_UPDATE_MANAGER_INFO`;

export const REQUEST_UPDATE_CREDIT_INFO = `${PREFIX}REQUEST_UPDATE_CREDIT_INFO`;
export const RECEIVE_UPDATE_CREDIT_INFO = `${PREFIX}RECEIVE_UPDATE_CREDIT_INFO`;

export const REQUEST_UPDATE_MANAGER_PASSWORD  = `${PREFIX}REQUEST_UPDATE_MANAGER_PASSWORD`;
export const RECEIVE_UPDATE_MANAGER_PASSWORD = `${PREFIX}RECEIVE_UPDATE_MANAGER_PASSWORD`;
