const PREFIX = '';

export const REQUEST_USER_LOGIN = `${PREFIX}REQUEST_USER_LOGIN`;
export const RECEIVE_USER_LOGIN = `${PREFIX}RECEIVE_USER_LOGIN`;

export const REQUEST_SEARCH_QUESTION_BANK = `${PREFIX}REQUEST_SEARCH_QUESTION_BANK`;
export const RECEIVE_SEARCH_QUESTION_BANK = `${PREFIX}RECEIVE_SEARCH_QUESTION_BANK`;

export const REQUEST_TEST_REGISTRATION = `${PREFIX}REQUEST_TEST_REGISTRATION`;
export const RECEIVE_TEST_REGISTRATION = `${PREFIX}RECEIVE_TEST_REGISTRATION`;

export const REQUEST_SEARCH_CANDIDATE_DATA = `${PREFIX}REQUEST_SEARCH_CANDIDATE_DATA`;
export const RECEIVE_SEARCH_CANDIDATE_DATA = `${PREFIX}RECEIVE_SEARCH_CANDIDATE_DATA`;

export const REQUEST_ALL_CANDIDATE = `${PREFIX}REQUEST_ALL_CANDIDATE`;
export const RECEIVE_ALL_CANDIDATE = `${PREFIX}RECEIVE_ALL_CANDIDATE`;


export const REQUEST_QUESTION_BANK_COUNT = `${PREFIX}REQUEST_QUESTION_BANK_COUNT`;
export const RECEIVE_QUESTION_BANK_COUNT = `${PREFIX}RECEIVE_QUESTION_BANK_COUNT`;

export const REQUEST_SEARCH_SUMMARY_DETAILS = `${PREFIX}REQUEST_SEARCH_SUMMARY_DETAILS`;
export const RECEIVE_SEARCH_SUMMARY_DETAILS = `${PREFIX}RECEIVE_SEARCH_SUMMARY_DETAILS`;

export const REQUEST_DOWNLOAD_REPORT = `${PREFIX}REQUEST_DOWNLOAD_REPORT`;
export const RECEIVE_DOWNLOAD_REPORT = `${PREFIX}RECEIVE_DOWNLOAD_REPORT`;

export const REQUEST_GET_ALL_TEST_ASSIGNMENT = `${PREFIX}REQUEST_GET_ALL_TEST_ASSIGNMENT`;
export const RECEIVE_GET_ALL_TEST_ASSIGNMENT = `${PREFIX}RECEIVE_GET_ALL_TEST_ASSIGNMENT`;

export const REQUEST_CATEGORY_GROUPING = `${PREFIX}REQUEST_CATEGORY_GROUPING`;
export const RECEIVE_CATEGORY_GROUPING = `${PREFIX}RECEIVE_CATEGORY_GROUPING`;

export const REQUEST_QUESTION_BANK_GROUPING = `${PREFIX}REQUEST_QUESTION_BANK_GROUPING`;
export const RECEIVE_QUESTION_BANK_GROUPING = `${PREFIX}RECEIVE_QUESTION_BANK_GROUPING`;

export const REQUEST_ALL_QUESTION_BANK = `${PREFIX}REQUEST_ALL_QUESTION_BANK`;
export const RECEIVE_ALL_QUESTION_BANK = `${PREFIX}RECEIVE_ALL_QUESTION_BANK`;

export const REQUEST_PARSE_FILE = `${PREFIX}REQUEST_PARSE_FILE`;
export const RECEIVE_PARSE_FILE = `${PREFIX}RECEIVE_PARSE_FILE`;

export const REQUEST_DOWNLOAD_TEMPLATE = `${PREFIX}REQUEST_DOWNLOAD_TEMPLATE`;
export const RECEIVE_DOWNLOAD_TEMPLATE = `${PREFIX}RECEIVE_DOWNLOAD_TEMPLATE`;

export const REQUEST_ADD_ALL_CANDIDATE = `${PREFIX}REQUEST_ADD_ALL_CANDIDATE`;
export const RECEIVE_ADD_ALL_CANDIDATE = `${PREFIX}RECEIVE_ADD_ALL_CANDIDATE`;

export const REQUEST_ADD_CANDIDATE = `${PREFIX}REQUEST_ADD_CANDIDATE`;
export const RECEIVE_ADD_CANDIDATE = `${PREFIX}RECEIVE_ADD_CANDIDATE`;

export const REQUEST_REJECT_TEST = `${PREFIX}REQUEST_REJECT_TEST`;
export const RECEIVE_REJECT_TEST = `${PREFIX}RECEIVE_REJECT_TEST`;

export const REQUEST_DECLARATIVE_ANSWER = `${PREFIX}REQUEST_DECLARATIVE_ANSWER`;
export const RECEIVE_DECLARATIVE_ANSWER = `${PREFIX}RECEIVE_DECLARATIVE_ANSWER`;

export const REQUEST_UPDATE_TEST = `${PREFIX}REQUEST_UPDATE_TEST`;
export const RECEIVE_UPDATE_TEST = `${PREFIX}RECEIVE_UPDATE_TEST`;

export const REQUEST_MANAGER_CREDITS = `${PREFIX}REQUEST_MANAGER_CREDITS`;
export const RECEIVE_MANAGER_CREDITS = `${PREFIX}RECEIVE_MANAGER_CREDITS`;

export const REQUEST_MANAGER_CREDITS_UPDATE = `${PREFIX}REQUEST_MANAGER_CREDITS_UPDATE`;
export const RECEIVE_MANAGER_CREDITS_UPDATE = `${PREFIX}RECEIVE_MANAGER_CREDITS_UPDATE`;

export const REQUEST_QUESTION_BANK_CASCADE  = `${PREFIX}REQUEST_QUESTION_BANK_CASCADE`;
export const RECEIVE_QUESTION_BANK_CASCADE = `${PREFIX}RECEIVE_QUESTION_BANK_CASCADE`;

export const REQUEST_UPDATE_CANDIDATE_PASSWORD  = `${PREFIX}REQUEST_UPDATE_CANDIDATE_PASSWORD`;
export const RECEIVE_UPDATE_CANDIDATE_PASSWORD = `${PREFIX}RECEIVE_UPDATE_CANDIDATE_PASSWORD`;

export const REQUEST_SEND_REPORT_MAIL  = `${PREFIX}REQUEST_SEND_REPORT_MAIL`;
export const RECEIVE_SEND_REPORT_MAIL = `${PREFIX}RECEIVE_SEND_REPORT_MAIL`;

/* export const REQUEST_USER_CREDENTIAL = `${PREFIX}REQUEST_USER_CREDENTIAL`;
export const RECEIVE_USER_CREDENTIAL = `${PREFIX}RECEIVE_USER_CREDENTIAL`;

export const REQUEST_USER_AUTHORITY_INFO = `${PREFIX}REQUEST_USER_AUTHORITY_INFO`;
export const RECEIVE_USER_AUTHORITY_INFO = `${PREFIX}RECEIVE_USER_AUTHORITY_INFO`;

export const REQUEST_USER_DETAIL = `${PREFIX}REQUEST_USER_DETAIL`;
export const RECEIVE_USER_DETAIL = `${PREFIX}RECEIVE_USER_DETAIL`;

export const REQUEST_ASSET_DETAIL = `${PREFIX}REQUEST_ASSET_DETAIL`;
export const RECEIVE_ASSET_DETAIL = `${PREFIX}RECEIVE_ASSET_DETAIL`;

export const REQUEST_DISTINCT_ASSET_DETAIL = `${PREFIX}REQUEST_DISTINCT_ASSET_DETAIL`;
export const RECEIVE_DISTINCT_ASSET_DETAIL = `${PREFIX}RECEIVE_DISTINCT_ASSET_DETAIL`;

export const REQUEST_LOCATION_DETAIL = `${PREFIX}REQUEST_LOCATION_DETAIL`;
export const RECEIVE_LOCATION_DETAIL = `${PREFIX}RECEIVE_LOCATION_DETAIL`;
*/
