const PREFIX = 'LAYOUT_';

export const REQUEST_SIDE_MENU_TOGGLE = `${PREFIX}REQUEST_SIDE_MENU_TOGGLE`;
export const RECEIVE_SIDE_MENU_TOGGLE = `${PREFIX}RECEIVE_SIDE_MENU_TOGGLE`;

export const REQUEST_USER_AUTHORITY = `${PREFIX}REQUEST_USER_AUTHORITY`;
export const RECEIVE_USER_AUTHORITY = `${PREFIX}RECEIVE_USER_AUTHORITY`;

export const REQUEST_USER_LOGOUT = `${PREFIX}REQUEST_USER_LOGOUT`;
